version: '3'

services:
  db:
    container_name: one16-challenge-db
    image: postgres:12.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: One16_db
      PGDATA: /tmp
  app:
    container_name: one16-challenge-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-local"
    ports:
      - '8080:8080'